name: PAN
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - torchaudio==0.13.0
  - python==3.10.8
  - pytorch-cuda==11.7
  - pytorch==1.13.0
  - torchvision==0.14.0
  - scikit-learn==1.0.1
  - pandas
  - matplotlib
  - openpyxl

