name: Update Article Citation Badges

on:
  push:
    branches:
      - dev
      - main
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  update-article-citations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Ensure it's the latest version for Node.js 20 support

      - name: Set up Python
        uses: actions/setup-python@v4  # Ensure it's the latest version for Node.js 20 support
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          sudo apt-get install -y jq
          pip install requests google-search-results

      - name: Fetch Google Scholar article citations
        env:
          SERPAPI_API_KEY: ${{ secrets.SERPAPI_API_KEY }}
        run: python scripts/fetch_article_citations.py

      - name: Update README with badges
        run: |
          # Read the badge_urls.json file
          badge_urls=$(jq -r 'to_entries | map("\(.key)=\(.value|tostring)") | join(",")' badge_urls.json)
          
          # Update the badge URLs in the README file
          while IFS=',' read -ra badges; do
            for badge in "${badges[@]}"; do
              IFS='=' read -r title url <<< "$badge"
              escaped_title=$(echo "$title" | sed 's/[^a-zA-Z0-9 ]//g' | tr '[:upper:]' '[:lower:]' | tr ' ' '-')
              sed -i "s|!\[$title Citations\](.*)|!\[$title Citations\]($url)|" README.md
            done
          done <<< "$badge_urls"

      - name: Commit and push changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add README.md article_citations.json badge_urls.json
          git commit -m "docs: update article citation badges"
          git push "https://${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:${{ github.ref }}