name: Update Article Citation Badges

on:
  push:
    branches:
      - dev
      - main
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  update-article-citations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Ensure it's the latest version for Node.js 20 support

      - name: Set up Python
        uses: actions/setup-python@v4  # Ensure it's the latest version for Node.js 20 support
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          sudo apt-get install -y jq
          pip install requests google-search-results

      - name: Fetch Google Scholar article citations
        env:
          SERPAPI_API_KEY: ${{ secrets.SERPAPI_API_KEY }}
        run: python scripts/fetch_article_citations.py

      - name: Update README with badges
        run: |
          BADGE_URLS=$(cat badge_urls.json)
          for row in $(echo "${BADGE_URLS}" | jq -r 'to_entries[] | @base64'); do
            _jq() {
              echo ${row} | base64 --decode | jq -r ${1}
            }
            TITLE=$(_jq '.key')
            URL=$(_jq '.value')
            TITLE_ESCAPED=$(echo $TITLE | sed 's/ /%20/g')
            sed -i "s|!\[$TITLE Citations\](.*)|!\[$TITLE Citations\]\($URL\)|" README.md
          done

      - name: Commit and push changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add README.md article_citations.json badge_urls.json
          git commit -m "docs: update article citation badges"
          git push "https://${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:${{ github.ref }}
